import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutWrapper from "@/app/layout-component/LayoutWrapper";
import { LoadingContextProvider } from "@/contexts/LoadingContext";
import { getSession } from "@/lib/utils/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vetch",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  // Read iron-session on the server
  const session = await getSession();
  const minimalSession = {
    isAuthenticated: Boolean(session.accessToken),
    user: session.user ?? null,
  };

  console.log(minimalSession);

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LoadingContextProvider>
            <LayoutWrapper session={minimalSession}>{children}</LayoutWrapper>
          </LoadingContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
